/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MonitorDimensions {
  width: number
  height: number
  index: number
}
export interface WindowInfo {
  className: string
  executable: string
  title: string
  pid: number
  productName?: string
  hwnd: number
  fullExe: string
  monitorDimensions: MonitorDimensions
  intersectsMultiple: boolean
  focused: boolean
  arguments: Array<string>
}
export declare function getAllWindows(): Array<WindowInfo>
